name: CI

on:
  push:
    paths:
      - '**.cairo'
      - 'devcontainer.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/carmineoptions/governance
          cacheFrom: ghcr.io/carmineoptions/governance
          push: always
          runCmd: cairo-format -cr

      - name: Run cairo-format
        uses: devcontainers/ci@v0.3
        with:
          runCmd: cairo-format -cr

      - name: Build with scarb
        uses: devcontainers/ci@v0.3
        with:
          runCmd: scarb build
